name: Update Release

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *' # Run the workflow every day at midnight

jobs:
  update-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch latest release yaml file name
        id: fetch-source-file
        run: |
          SOURCE_FILE=$(curl -sL "https://github.com/shipwright-io/build/releases/download/nightly/latest.txt")
          SOURCE_FILE="nightly-$SOURCE_FILE.yaml"
          echo "SOURCE_FILE=$SOURCE_FILE" >> $GITHUB_ENV

      - name: Save file content
        id: save-file-content
        run: |
          curl -sL "https://github.com/shipwright-io/build/releases/download/nightly/${{ env.SOURCE_FILE }}" -o ${{ env.SOURCE_FILE }}

      - name: Update content in shipwright-io/operator at kodata/release.yaml
        run: |
          cat "${{ env.SOURCE_FILE }}" > kodata/release.yaml
          # Remove file
          rm "${{ env.SOURCE_FILE }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update kodata/release.yaml from shipwright-io/build nightly"
          title: "Update kodata/release.yaml from shipwright-io/build nightly"
          body: "This is an automated pull request which updates kodata/release.yaml with the content from shipwright-io/build nightly."
          branch: "update-release-yaml"
          delete-branch: "true"
          base: "main"